Add CI: tcl9, memleak

diff --git a/.github/workflows/memleaks.yml b/.github/workflows/memleaks.yml
--- a/.github/workflows/memleaks.yml
+++ b/.github/workflows/memleaks.yml
@@ -1,4 +1,4 @@
-name: Linux
+name: Memory leak checker
 on: [push]
 permissions:
   contents: read
@@ -9,21 +9,36 @@ jobs:
   build:
     runs-on: ubuntu-24.04
     timeout-minutes: 5
-    strategy:
-      matrix:
-        compiler: ["gcc", "clang"]
-    name: build (${{ matrix.compiler }})
     steps:
 
-      - name: Setup Environment (compiler=${{ matrix.compiler }})
+      - name: Checkout Tcl
+        uses: actions/checkout@v4
+        with:
+          repository: tcltk/tcl
+          ref: core-8-6-14
+          path: tcl
+      - name: Configure Tcl
+        working-directory: tcl/unix
         run: |
-          sudo apt-get install tcl8.6-dev cmake
-          mkdir "$HOME/install dir"
-          echo "CFGOPT_COMMON=--with-tcl=/usr/lib/tcl8.6" >> $GITHUB_ENV
-          echo "CC=$COMPILER" >> $GITHUB_ENV
-        env:
-          COMPILER: ${{ matrix.compiler }}
-          OPTS: ${{ matrix.compiler }}
+          ./configure --enable-symbols=all --prefix=$HOME/root || {
+            cat config.log
+            echo "::error::Failure during Configure Tcl"
+            exit 1
+          }
+      - name: Build Tcl
+        working-directory: tcl/unix
+        run: |
+          make -j || {
+            echo "::error::Failure during Build Tcl"
+            exit 1
+          }
+      - name: Install Tcl
+        working-directory: tcl/unix
+        run: |
+          make install || {
+            echo "::error::Failure during Install Tcl"
+            exit 1
+          }
 
       - name: Checkout cJSON
         uses: actions/checkout@v4
@@ -60,7 +75,7 @@ jobs:
         run: |
           mkdir build
           cd build
-          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/root -DCMAKE_PREFIX_PATH=$HOME/root -DTCL_INCLUDE_DIR=/usr/include/tcl8.6 -DTCL_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu
+          CFLAGS="-DTCL_MEM_DEBUG=1 -g" cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/root -DCMAKE_PREFIX_PATH=$HOME/root -DTCL_INCLUDE_DIR=$HOME/root/include -DTCL_LIBRARY_DIR=$HOME/root/lib
       - name: Build
         working-directory: build
         run: |
@@ -71,7 +86,7 @@ jobs:
       - name: Run Tests
         working-directory: build
         run: |
-          LD_LIBRARY_PATH="$HOME/root/lib" make test || {
+          LD_LIBRARY_PATH="$HOME/root/lib" MEMDEBUG=1 make test || {
             echo "::error::Failure during Test"
             exit 1
           }
